"use client";

import { useState, useMemo, useEffect } from "react";
import { X, Plus, ShieldCheck, RotateCcw, Eye, EyeOff } from "lucide-react";
import type { CreateUserInput } from "@/contexts/control-panel-context";
import type { RoleId, CustomPermissions } from "@/types/user";
import { ROLES } from "@/types/user";
import { useGarages } from "@/contexts/control-panel-context";
import { ROLE_PERMISSIONS } from "@/contexts/auth-context";
import { userSchema, type UserFormData } from "@/lib/schemas";

type AddUserModalProps = {
  onSubmit: (user: CreateUserInput, customId?: string) => void;
  onClose: () => void;
  existingUsernames?: string[];
  existingIds?: string[];
};

const CORE_PERMS: { key: keyof CustomPermissions; label: string; desc: string }[] = [
  { key: "canEdit",         label: "Edit Records",    desc: "Add / edit / delete bikes and drivers" },
  { key: "canClockDriver",  label: "Clock Drivers",   desc: "Clock drivers in/out from Dashboard" },
];

const PAGE_PERMS: { key: keyof CustomPermissions; label: string; desc: string }[] = [
  { key: "canViewDashboard", label: "Dashboard Page", desc: "Access the dashboard and fleet overview" },
  { key: "canViewGarages",   label: "Garages Page",   desc: "Access the list of all garages and locations" },
  { key: "canViewBikes",     label: "Bikes Page",     desc: "Access fleet bikes and maintenance" },
  { key: "canViewDrivers",   label: "Drivers Page",   desc: "Access driver profiles and check shifts" },
  { key: "canViewReports",   label: "Reports Page",   desc: "Access the analytics and reports page" },
  { key: "canViewSettings",  label: "Settings Page",  desc: "Access the system configuration page" },
  { key: "canManageUsers",   label: "Control Panel",  desc: "Access operations and manage users" },
];

export function AddUserModal({ onSubmit, onClose, existingUsernames = [], existingIds = [] }: AddUserModalProps) {
  const { garages } = useGarages();
  const [name, setName] = useState("");
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [showPass, setShowPass] = useState(false);
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [role, setRole] = useState<RoleId>("observer");
  const [garageId, setGarageId] = useState("");
  const [customPerms, setCustomPerms] = useState<CustomPermissions>({});
  const [validationErrors, setValidationErrors] = useState<Record<string, string>>({});

  const [customId, setCustomId] = useState("");

  // Generate next available ID
  const autoGeneratedId = useMemo(() => {
    const prefix = "USR-";
    let counter = 1;
    let newId = `${prefix}${String(counter).padStart(3, "0")}`;
    while (existingIds.includes(newId)) {
      counter++;
      newId = `${prefix}${String(counter).padStart(3, "0")}`;
    }
    return newId;
  }, [existingIds]);

  // Auto-fill the generated ID when modal opens
  useEffect(() => {
    if (!customId && autoGeneratedId) {
      setCustomId(autoGeneratedId);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [autoGeneratedId]);

  // Duplicate checks
  const isDuplicateId = customId.trim() !== "" && existingIds.filter(id => id !== autoGeneratedId).includes(customId.trim());
  const isDuplicateUsername = username.trim() !== "" && existingUsernames.includes(username.trim().toLowerCase());

  function handleRoleChange(newRole: RoleId) {
    setRole(newRole);
    if (newRole !== "garage") setGarageId("");
    setCustomPerms({});
  }

  function togglePerm(key: keyof CustomPermissions) {
    const base = ROLE_PERMISSIONS[role][key];
    const current = customPerms[key] ?? base;
    const next = !current;
    if (next === base) {
      setCustomPerms((p) => { const c = { ...p }; delete c[key]; return c; });
    } else {
      setCustomPerms((p) => ({ ...p, [key]: next }));
    }
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setValidationErrors({});
    
    if (isDuplicateUsername || isDuplicateId) return;
    
    // Validate with Zod
    const formData: UserFormData = {
      name,
      username,
      password,
      email: email || undefined,
      phone: phone || undefined,
      role,
      garageId: role === "garage" ? garageId : undefined,
      customPermissions: Object.keys(customPerms).length > 0 ? customPerms : undefined,
    };
    
    const result = userSchema.safeParse(formData);
    if (!result.success) {
      const errors: Record<string, string> = {};
      result.error.issues.forEach((err) => {
        if (err.path[0]) {
          errors[err.path[0] as string] = err.message;
        }
      });
      setValidationErrors(errors);
      return;
    }
    
    // Password is hashed server-side
    const payload: CreateUserInput = { name, username, password, email, phone, role };
    if (role === "garage" && garageId) payload.garageId = garageId;
    if (Object.keys(customPerms).length > 0) payload.customPermissions = customPerms;
    onSubmit(payload, customId.trim() || undefined);
    onClose();
  }

  const hasOverrides = Object.keys(customPerms).length > 0;

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-surface-950/60 backdrop-blur-sm" />
      <div className="relative w-full max-w-lg overflow-hidden rounded-3xl bg-white shadow-2xl ring-1 ring-black/5">
        {/* Header */}
        <div className="relative bg-gradient-to-br from-surface-900 to-surface-800 p-5 text-white">
          <div className="absolute inset-0 opacity-10" style={{ backgroundImage: "radial-gradient(circle at 20% 30%, #fff 1px, transparent 1px)", backgroundSize: "24px 24px" }} />
          <div className="relative flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white/10 ring-1 ring-white/20">
                <ShieldCheck className="h-5 w-5" />
              </div>
              <h3 className="text-lg font-bold tracking-tight">Add New User</h3>
            </div>
            <button type="button" onClick={onClose} className="inline-flex h-8 w-8 items-center justify-center rounded-xl bg-white/10 text-slate-300 ring-1 ring-white/15 transition-colors hover:bg-white/20 hover:text-white">
              <X className="h-4 w-4" />
            </button>
          </div>
        </div>

        <div className="max-h-[80vh] overflow-y-auto">
        <form onSubmit={handleSubmit} className="space-y-4 p-6">
          {/* User ID */}
          <div className="space-y-1.5">
            <label className="text-sm font-medium text-surface-900">
              User ID <span className="text-slate-400 text-xs font-normal">(optional)</span>
            </label>
            <input
              type="text"
              value={customId}
              onChange={(e) => setCustomId(e.target.value.replace(/\s+/g, ""))}
              placeholder="e.g. USR-001 (auto-generated if empty)"
              className={`w-full rounded-xl border bg-white px-3 py-2 text-sm text-surface-900 placeholder:text-slate-400 outline-none focus:ring-2 ${
                isDuplicateId
                  ? "border-rose-400 focus:border-rose-400 focus:ring-rose-100"
                  : customId.trim() && !isDuplicateId
                  ? "border-emerald-400 focus:border-emerald-400 focus:ring-emerald-100"
                  : "border-surface-200 focus:border-brand-400 focus:ring-brand-100"
              }`}
            />
            {isDuplicateId && (
              <p className="text-xs text-rose-500 flex items-center gap-1">
                <span className="inline-block w-1.5 h-1.5 rounded-full bg-rose-500" />
                This ID already exists. Please choose a different one.
              </p>
            )}
            {customId.trim() && !isDuplicateId && (
              <p className="text-xs text-emerald-600 flex items-center gap-1">
                <span className="inline-block w-1.5 h-1.5 rounded-full bg-emerald-500" />
                ID is available
              </p>
            )}
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-surface-900">
                Full Name
              </label>
              <input
                type="text"
                required
                value={name}
                onChange={(e) => { setName(e.target.value); setValidationErrors(prev => ({ ...prev, name: '' })); }}
                placeholder="e.g. Ahmed Hassan"
                className={`w-full rounded-xl border bg-white px-3 py-2 text-sm text-surface-900 placeholder:text-slate-400 outline-none focus:ring-2 ${
                  validationErrors.name ? "border-rose-400 focus:border-rose-400 focus:ring-rose-100" : "border-surface-200 focus:border-brand-400 focus:ring-brand-100"
                }`}
              />
              {validationErrors.name && <p className="text-xs text-rose-500">{validationErrors.name}</p>}
            </div>

            <div className="space-y-1.5">
              <label className="text-sm font-medium text-surface-900">
                Email <span className="text-slate-400 text-xs font-normal">(optional)</span>
              </label>
              <input
                type="email"
                value={email}
                onChange={(e) => { setEmail(e.target.value); setValidationErrors(prev => ({ ...prev, email: '' })); }}
                placeholder="e.g. ahmed@email.com"
                className={`w-full rounded-xl border bg-white px-3 py-2 text-sm text-surface-900 placeholder:text-slate-400 outline-none focus:ring-2 ${
                  validationErrors.email ? "border-rose-400 focus:border-rose-400 focus:ring-rose-100" : "border-surface-200 focus:border-brand-400 focus:ring-brand-100"
                }`}
              />
              {validationErrors.email && <p className="text-xs text-rose-500">{validationErrors.email}</p>}
            </div>
          </div>

          {/* Login credentials */}
          <div className="rounded-xl border border-brand-100 bg-brand-50/40 p-4 space-y-3">
            <p className="text-xs font-bold uppercase tracking-wider text-brand-700">Login Credentials</p>
            <div className="grid gap-3 sm:grid-cols-2">
              <div className="space-y-1.5">
                <label className="text-sm font-medium text-surface-900">Username</label>
                <input
                  type="text"
                  required
                  value={username}
                  onChange={(e) => { setUsername(e.target.value.toLowerCase().replace(/\s+/g, "")); setValidationErrors(prev => ({ ...prev, username: '' })); }}
                  placeholder="e.g. ahmed"
                  autoComplete="off"
                  className={`w-full rounded-xl border bg-white px-3 py-2 text-sm text-surface-900 placeholder:text-slate-400 outline-none focus:ring-2 ${
                    isDuplicateUsername || validationErrors.username
                      ? "border-rose-400 focus:border-rose-400 focus:ring-rose-100"
                      : username.trim() && !isDuplicateUsername
                      ? "border-emerald-400 focus:border-emerald-400 focus:ring-emerald-100"
                      : "border-surface-200 focus:border-brand-400 focus:ring-brand-100"
                  }`}
                />
                {isDuplicateUsername && (
                  <p className="text-xs text-rose-500 flex items-center gap-1">
                    <span className="inline-block w-1.5 h-1.5 rounded-full bg-rose-500" />
                    This username already exists. Please choose a different one.
                  </p>
                )}
                {validationErrors.username && <p className="text-xs text-rose-500">{validationErrors.username}</p>}
                {username.trim() && !isDuplicateUsername && !validationErrors.username && (
                  <p className="text-xs text-emerald-600 flex items-center gap-1">
                    <span className="inline-block w-1.5 h-1.5 rounded-full bg-emerald-500" />
                    Username is available
                  </p>
                )}
              </div>
              <div className="space-y-1.5">
                <label className="text-sm font-medium text-surface-900">Password</label>
                <div className="relative">
                  <input
                    type={showPass ? "text" : "password"}
                    required
                    value={password}
                    onChange={(e) => { setPassword(e.target.value); setValidationErrors(prev => ({ ...prev, password: '' })); }}
                    placeholder="e.g. pass123"
                    autoComplete="new-password"
                    className={`w-full rounded-xl border bg-white px-3 py-2 pr-10 text-sm text-surface-900 placeholder:text-slate-400 outline-none focus:ring-2 ${
                      validationErrors.password ? "border-rose-400 focus:border-rose-400 focus:ring-rose-100" : "border-surface-200 focus:border-brand-400 focus:ring-brand-100"
                    }`}
                  />
                  <button
                    type="button"
                    onClick={() => setShowPass(!showPass)}
                    className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600 transition-colors"
                    tabIndex={-1}
                  >
                    {showPass ? <EyeOff size={16} /> : <Eye size={16} />}
                  </button>
                </div>
                {validationErrors.password && <p className="text-xs text-rose-500">{validationErrors.password}</p>}
              </div>
            </div>
          </div>

          <div className="space-y-1.5">
            <label className="text-sm font-medium text-surface-900">
              Phone
            </label>
            <input
              type="tel"
              value={phone}
              onChange={(e) => { setPhone(e.target.value); setValidationErrors(prev => ({ ...prev, phone: '' })); }}
              placeholder="e.g. +964 770 123 4567"
              className={`w-full rounded-xl border bg-white px-3 py-2 text-sm text-surface-900 placeholder:text-slate-400 outline-none focus:ring-2 ${
                validationErrors.phone ? "border-rose-400 focus:border-rose-400 focus:ring-rose-100" : "border-surface-200 focus:border-brand-400 focus:ring-brand-100"
              }`}
            />
            {validationErrors.phone && <p className="text-xs text-rose-500">{validationErrors.phone}</p>}
          </div>

          <div className="space-y-1.5">
            <label className="text-sm font-medium text-surface-900">Role</label>
            <select
              value={role}
              onChange={(e) => handleRoleChange(e.target.value as RoleId)}
              className="w-full rounded-xl border border-surface-200 bg-white px-3 py-2 text-sm text-surface-900 outline-none focus:border-brand-400 focus:ring-2 focus:ring-brand-100"
            >
              {ROLES.map((r) => (
                <option key={r.id} value={r.id}>{r.label}</option>
              ))}
            </select>
          </div>

          {/* ── Permissions ──────────────────────────────────────── */}
          <div className="rounded-2xl border border-violet-100 bg-violet-50/40 p-4 space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <ShieldCheck className="h-4 w-4 text-violet-600" />
                <p className="text-xs font-bold uppercase tracking-wider text-violet-700">Permissions</p>
              </div>
              {hasOverrides && (
                <button type="button" onClick={() => setCustomPerms({})} className="flex items-center gap-1 rounded-lg px-2 py-1 text-[11px] font-semibold text-slate-500 hover:bg-white hover:text-slate-700 transition-colors">
                  <RotateCcw className="h-3 w-3" />
                  Reset to role defaults
                </button>
              )}
            </div>
            <div className="space-y-4">
              {/* Actions & Operations */}
              <div className="space-y-2">
                <p className="text-[11px] font-bold uppercase tracking-wider text-violet-500 px-1">Actions & Operations</p>
                {CORE_PERMS.map(({ key, label, desc }) => {
                  const base = ROLE_PERMISSIONS[role][key];
                  const effective = customPerms[key] ?? base;
                  const isOverridden = customPerms[key] !== undefined;
                  return (
                    <button key={key} type="button" onClick={() => togglePerm(key)}
                      className={`flex w-full items-center gap-3 rounded-xl px-3 py-2 text-left transition-all ${
                        effective ? "bg-white ring-1 ring-violet-200 shadow-sm" : "bg-white/50 ring-1 ring-surface-200"
                      }`}
                    >
                      <div className={`relative h-5 w-9 shrink-0 rounded-full transition-colors ${
                        effective ? "bg-violet-600" : "bg-surface-300"
                      }`}>
                        <div className={`absolute top-0.5 h-4 w-4 rounded-full bg-white shadow transition-transform ${
                          effective ? "translate-x-4" : "translate-x-0.5"
                        }`} />
                      </div>
                      <div className="min-w-0 flex-1">
                        <div className="flex items-center gap-1.5">
                          <span className={`text-sm font-semibold ${
                            effective ? "text-surface-900" : "text-slate-400"
                          }`}>{label}</span>
                          {isOverridden && (
                            <span className={`rounded-full px-1.5 py-0.5 text-[10px] font-bold ${
                              effective !== base ? "bg-amber-100 text-amber-700" : "bg-surface-100 text-slate-400"
                            }`}>{effective ? "granted" : "revoked"}</span>
                          )}
                        </div>
                        <p className="text-[11px] text-slate-400">{desc}</p>
                      </div>
                      {!isOverridden && <span className="shrink-0 text-[10px] font-medium text-slate-400">default</span>}
                    </button>
                  );
                })}
              </div>

              {/* Page Visibility */}
              <div className="space-y-2">
                <p className="text-[11px] font-bold uppercase tracking-wider text-violet-500 px-1">Page Visibility</p>
                {PAGE_PERMS.map(({ key, label, desc }) => {
                  const base = ROLE_PERMISSIONS[role][key];
                  const effective = customPerms[key] ?? base;
                  const isOverridden = customPerms[key] !== undefined;
                  return (
                    <button key={key} type="button" onClick={() => togglePerm(key)}
                      className={`flex w-full items-center gap-3 rounded-xl px-3 py-2 text-left transition-all ${
                        effective ? "bg-white ring-1 ring-violet-200 shadow-sm" : "bg-white/50 ring-1 ring-surface-200"
                      }`}
                    >
                      <div className={`relative h-5 w-9 shrink-0 rounded-full transition-colors ${
                        effective ? "bg-violet-600" : "bg-surface-300"
                      }`}>
                        <div className={`absolute top-0.5 h-4 w-4 rounded-full bg-white shadow transition-transform ${
                          effective ? "translate-x-4" : "translate-x-0.5"
                        }`} />
                      </div>
                      <div className="min-w-0 flex-1">
                        <div className="flex items-center gap-1.5">
                          <span className={`text-sm font-semibold ${
                            effective ? "text-surface-900" : "text-slate-400"
                          }`}>{label}</span>
                          {isOverridden && (
                            <span className={`rounded-full px-1.5 py-0.5 text-[10px] font-bold ${
                              effective !== base ? "bg-amber-100 text-amber-700" : "bg-surface-100 text-slate-400"
                            }`}>{effective ? "granted" : "revoked"}</span>
                          )}
                        </div>
                        <p className="text-[11px] text-slate-400">{desc}</p>
                      </div>
                      {!isOverridden && <span className="shrink-0 text-[10px] font-medium text-slate-400">default</span>}
                    </button>
                  );
                })}
              </div>
            </div>
          </div>

          {role === "garage" && (
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-surface-900">
                Assigned Garage
              </label>
              <select
                required
                value={garageId}
                onChange={(e) => setGarageId(e.target.value)}
                className="w-full rounded-xl border border-surface-200 bg-white px-3 py-2 text-sm text-surface-900 outline-none focus:border-brand-400 focus:ring-2 focus:ring-brand-100"
              >
                <option value="">Select a garage</option>
                {garages.map((g) => (
                  <option key={g.id} value={g.id}>
                    {g.name}
                  </option>
                ))}
              </select>
            </div>
          )}

          <div className="flex justify-end gap-3 pt-2">
            <button type="button" onClick={onClose} className="rounded-xl border border-surface-200 bg-white px-4 py-2.5 text-sm font-medium text-surface-700 transition-colors hover:bg-surface-50">
              Cancel
            </button>
            <button
              type="submit"
              disabled={isDuplicateUsername || isDuplicateId}
              className={`inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold shadow-md transition-all active:scale-[0.98] ${
                isDuplicateUsername || isDuplicateId
                  ? "bg-surface-200 text-slate-400 cursor-not-allowed"
                  : "bg-brand-600 text-white shadow-brand-200 hover:bg-brand-700"
              }`}
            >
              <Plus className="h-4 w-4" />
              Add User
            </button>
          </div>
        </form>
        </div>
      </div>
    </div>
  );
}
