"use client";

import { useState, useMemo, useEffect } from "react";
import { X, Plus } from "lucide-react";
import type { Garage } from "@/types/garage";
import { useUsers } from "@/contexts/control-panel-context";

type AddGarageModalProps = {
  onSubmit: (garage: Omit<Garage, "id">, customId?: string) => void;
  onClose: () => void;
  existingNames?: string[];
  existingIds?: string[];
};

export function AddGarageModal({ onSubmit, onClose, existingNames = [], existingIds = [] }: AddGarageModalProps) {
  const { users } = useUsers();
  const garageManagers = users.filter((u) => u.role === "garage");

  const [customId, setCustomId] = useState("");
  const [name, setName] = useState("");
  const [location, setLocation] = useState("");
  const [capacity, setCapacity] = useState(1);
  const [managerId, setManagerId] = useState("");

  // Generate next available ID
  const autoGeneratedId = useMemo(() => {
    const prefix = "GRG-";
    let counter = 1;
    let newId = `${prefix}${String(counter).padStart(3, "0")}`;
    while (existingIds.includes(newId)) {
      counter++;
      newId = `${prefix}${String(counter).padStart(3, "0")}`;
    }
    return newId;
  }, [existingIds]);

  // Auto-fill the generated ID when modal opens
  useEffect(() => {
    if (!customId && autoGeneratedId) {
      setCustomId(autoGeneratedId);
    }
  }, [autoGeneratedId]);

  // Duplicate checks
  const isDuplicateId = customId.trim() !== "" && existingIds.filter(id => id !== autoGeneratedId).includes(customId.trim());
  const isDuplicateName = name.trim() !== "" && existingNames.includes(name.trim().toLowerCase());

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!name.trim()) return;
    if (isDuplicateName || isDuplicateId) return;
    const payload: Omit<Garage, "id"> = { name, location, capacity };
    if (managerId) payload.managerId = managerId;
    onSubmit(payload, customId.trim() || undefined);
    onClose();
  }

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center p-4">
      <div
        className="absolute inset-0 bg-surface-950/60 backdrop-blur-sm"
      />
      <div className="relative w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl">
        <div className="mb-5 flex items-center justify-between">
          <h3 className="text-lg font-semibold text-surface-900">
            Add New Garage
          </h3>
          <button
            type="button"
            onClick={onClose}
            className="inline-flex h-8 w-8 items-center justify-center rounded-lg text-slate-400 hover:bg-surface-100 hover:text-surface-700"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          {/* ID + Name */}
          <div className="grid gap-4 sm:grid-cols-[1fr_2fr]">
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-surface-900">
                Garage ID <span className="text-slate-400 text-xs font-normal">(auto)</span>
              </label>
              <input
                type="text"
                value={customId}
                onChange={(e) => setCustomId(e.target.value.replace(/\s+/g, ""))}
                placeholder="e.g. GRG-001"
                className={`w-full rounded-xl border bg-white px-3 py-2 text-sm text-surface-900 placeholder:text-slate-400 outline-none focus:ring-2 ${
                  isDuplicateId
                    ? "border-rose-400 focus:border-rose-400 focus:ring-rose-100"
                    : customId.trim() && !isDuplicateId
                    ? "border-emerald-400 focus:border-emerald-400 focus:ring-emerald-100"
                    : "border-surface-200 focus:border-brand-400 focus:ring-brand-100"
                }`}
              />
              {isDuplicateId && (
                <p className="text-xs text-rose-500 flex items-center gap-1">
                  <span className="inline-block w-1.5 h-1.5 rounded-full bg-rose-500" />
                  ID exists
                </p>
              )}
            </div>
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-surface-900">Garage Name</label>
              <input
                type="text"
                required
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="e.g. Central Hub"
                className={`w-full rounded-xl border bg-white px-3 py-2 text-sm text-surface-900 placeholder:text-slate-400 outline-none focus:ring-2 ${
                  isDuplicateName
                    ? "border-rose-400 focus:border-rose-400 focus:ring-rose-100"
                    : name.trim() && !isDuplicateName
                    ? "border-emerald-400 focus:border-emerald-400 focus:ring-emerald-100"
                    : "border-surface-200 focus:border-brand-400 focus:ring-brand-100"
                }`}
              />
              {isDuplicateName && (
                <p className="text-xs text-rose-500 flex items-center gap-1">
                  <span className="inline-block w-1.5 h-1.5 rounded-full bg-rose-500" />
                  Name exists
                </p>
              )}
            </div>
          </div>

          {/* Location */}
          <div className="space-y-1.5">
            <label className="text-sm font-medium text-surface-900">Location</label>
            <input
              type="text"
              required
              value={location}
              onChange={(e) => setLocation(e.target.value)}
              placeholder="e.g. Main Street"
              className="w-full rounded-xl border border-surface-200 bg-white px-3 py-2 text-sm text-surface-900 placeholder:text-slate-400 outline-none focus:border-brand-400 focus:ring-2 focus:ring-brand-100"
            />
          </div>

          {/* Capacity + Manager */}
          <div className="grid gap-4 sm:grid-cols-[1fr_2fr]">
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-surface-900">Capacity</label>
              <input
                type="number"
                required
                min={1}
                value={capacity}
                onChange={(e) => setCapacity(Number(e.target.value))}
                className="w-full rounded-xl border border-surface-200 bg-white px-3 py-2 text-sm text-surface-900 outline-none focus:border-brand-400 focus:ring-2 focus:ring-brand-100"
              />
            </div>
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-surface-900">Manager</label>
              <select
                value={managerId}
                onChange={(e) => setManagerId(e.target.value)}
                className="w-full rounded-xl border border-surface-200 bg-white px-3 py-2 text-sm text-surface-900 outline-none focus:border-brand-400 focus:ring-2 focus:ring-brand-100"
              >
                <option value="">Select a manager</option>
                {garageManagers.map((u) => (
                  <option key={u.id} value={u.id}>
                    {u.name}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <div className="flex justify-end gap-3 pt-2">
            <button
              type="button"
              onClick={onClose}
              className="rounded-xl border border-surface-200 bg-white px-4 py-2.5 text-sm font-medium text-surface-700 transition-colors hover:bg-surface-50"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isDuplicateName || isDuplicateId}
              className={`inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-medium transition-colors focus:outline-none focus:ring-2 ${
                isDuplicateName || isDuplicateId
                  ? "bg-surface-200 text-slate-400 cursor-not-allowed"
                  : "bg-brand-600 text-white hover:bg-brand-700 focus:ring-brand-300"
              }`}
            >
              <Plus className="h-4 w-4" />
              Add Garage
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
